Web/Controllers/StatementAccountController.cs
using ApplicationCore.Services;
using Infrastructure.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Security;
using Web.Utils;

namespace Web.Controllers
{
    public class StatementAccountController : Controller
    {
        // GET: StatementAccount
        [CustomAuthorize((int)UserRoles.Administrator)]
        public ActionResult Index()
        {
            IEnumerable<Residence> list = null;
            try
            {
                IServiceResidence _ServiceResidence = new ServiceResidence();
                list = _ServiceResidence.GetResidences();
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error at procesing data: " + ex.Message;
                return RedirectToAction("Default", "Error");
            }
            return View(list);
        }
        

        public ActionResult Details(int? id)
        {
            IServiceResidence _ServiceResidence = new ServiceResidence();
            Residence oResidence = null;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }
                oResidence = _ServiceResidence.GetResidenceByID(Convert.ToInt32(id));
                if (oResidence == null)
                {
                    TempData["Message"] = "The requested residence does not exist";
                    //Controlador
                    TempData["Redirect"] = "Residence";
                    //Acción
                    TempData["Redirect-Action"] = "Index";
                    return RedirectToAction("Default", "Error");
                }
                return View(oResidence);
            }
            catch (Exception ex)
            {

                TempData["Message"] = "Error at procesing data: " + ex.Message;
                //Controlador
                TempData["Redirect"] = "Residence";
                //Acción
                TempData["Redirect-Action"] = "Index";
                return RedirectToAction("Default", "Error");
            }
        }

        public ActionResult PayDebts()
        {
            IServiceResidence _ServiceResidence = new ServiceResidence();
            
            Residence oResidence;
            try
            {
                oResidence = _ServiceResidence.GetResidenceByUser(GetSessionUser().IDUser);
                if (oResidence == null)
                {
                    TempData["Message"] = "The requested data had a problem";
                    //Controlador
                    TempData["Redirect"] = "Index";
                    //Acción
                    TempData["Redirect-Action"] = "Index";
                    return RedirectToAction("Default", "Error");
                }
                ViewBag.PendingDebts = listDebts(oResidence.IDResidence); 
                return View(oResidence);
            }
            catch (Exception ex)
            {
                TempData["Message"] = "Error at procesing data: " + ex.Message;
                //Controlador
                TempData["Redirect"] = "Residence";
                //Acción
                TempData["Redirect-Action"] = "Index";
                return RedirectToAction("Default", "Error");
            }
        }

        public ActionResult SetDebtsAsPaid(string[] selectedDebts) 
        {
            IServicePlanAssignment _ServicePlanAssignment = new ServicePlanAssignment();
            IServiceResidence _ServiceResidence = new ServiceResidence();
            try
            {

                _ServicePlanAssignment.SetDebtsAsPaid(selectedDebts);
                

                ViewBag.PendingDebts = listDebts(_ServiceResidence.GetResidenceByUser(GetSessionUser().IDUser).IDResidence);
                return RedirectToAction("PayDebts");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error at procesing data: " + ex.Message;
                TempData["Redirect"] = "PaymentPlan";
                TempData["Redirect-Action"] = "Maintenance";
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }
    

        private User GetSessionUser()
        {
            User oUser = null;
            //Validar si existe la Session
            if (Session["user"] != null)
            {
                oUser = (User)Session["User"];
            }
            return oUser;
        }

        private MultiSelectList listDebts(int idResidence)
        {
            IServicePlanAssignment _ServicePlanAssignment = new ServicePlanAssignment();
            IEnumerable<PlanAssignment> list = _ServicePlanAssignment.GetDebtsByResidence(idResidence);

            return new MultiSelectList(list, "IDAssignment", "Description");
        }
    }
}

Web/Views/StatementAccount/Details.cshtml
@model Infrastructure.Models.Residence

@{
    ViewBag.Title = "Details";
}

<div>
    <h4>Statement Account</h4>
    <hr />

    <div class="d-flex bd-highlight">
        <div class="p-2 flex-fill bd-highlight">
            <dl class="dl-horizontal">
                <dt>User Info</dt>

                <dd>
                    @Html.DisplayNameFor(model => model.User.IDUser): @Html.DisplayFor(model => model.User.IDUser)
                </dd>

                <dd>
                    Name: @Html.DisplayFor(model => model.User.FirstName) @Html.DisplayFor(model => model.User.LastName)
                </dd>

                <dd>
                    @Html.DisplayNameFor(model => model.User.Email): @Html.DisplayFor(model => model.User.Email)
                </dd>
            </dl>
        </div>

        <div class="p-2 flex-fill bd-highlight">
            <dl class="dl-horizontal">
                <dt>Residence Info</dt>

                <dd>
                    @Html.DisplayNameFor(model => model.IDResidence): @Html.DisplayFor(model => model.IDResidence)
                </dd>

                <dd>
                    @Html.DisplayNameFor(model => model.StartYear): @Html.DisplayFor(model => model.StartYear)
                </dd>

                <dd>
                    @if (Model.PlanAssignment.Count == 0)
                    {
                        <p>Actual Plan: Not assigned yet</p>
                    }
                    else
                    {
                        <p>Actual Plan: @Html.DisplayFor(model => model.PlanAssignment.Last().PaymentPlan.Name)</p>
                    }

                </dd>
            </dl>
        </div>
    </div>


    <hr />
    <div class="d-flex justify-content-between my-4" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample"><h4>Payment History</h4><i class="fa-solid fa-chevron-down"></i></div>
    <hr />

    <div class="collapse" id="collapseExample">
        <table id="myTable" class="table">
            <thead>
                <tr>
                    <th>

                        @Html.DisplayNameFor(model => model.PlanAssignment.Last().AssignmentDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PlanAssignment.Last().PayedStatus)
                    </th>
                    <th>

                        @Html.DisplayNameFor(model => model.PlanAssignment.Last().Amount)

                    </th>
                    <th>Plan</th>
                    <th>Items</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model.PlanAssignment)
                {
                    if (item.PayedStatus == true)
                    {
                        <tr>

                            <td>
                                @Html.DisplayFor(modelItem => item.AssignmentDate)
                            </td>
                            <td>
                                <p style="color:green;">Payed</p>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Amount)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PaymentPlan.Name)
                            </td>
                            <td>
                                @foreach (var pItem in item.PaymentPlan.PaymentItem)
                                {
                                    <span>@Html.DisplayFor(model => pItem.Description) |</span>
                                }
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>


    <div class="d-flex justify-content-between my-4 collapsible1" data-bs-toggle="collapse" href="#collapseDebts" role="button" aria-expanded="false" aria-controls="collapseDebts"><h4>Debts</h4><i class="fa-solid fa-chevron-down"></i></div>
    <hr />

    <div class="collapse" id="collapseDebts">
        <table id="DebtsTable" class="table">
            <thead>
                <tr>
                    <th>

                        @Html.DisplayNameFor(model => model.PlanAssignment.Last().AssignmentDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PlanAssignment.Last().PayedStatus)
                    </th>
                    <th>

                        @Html.DisplayNameFor(model => model.PlanAssignment.Last().Amount)

                    </th>
                    <th>Plan</th>
                    <th>Items</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model.PlanAssignment)
                {
                    if (item.PayedStatus == false)
                    {
                        <tr>

                            <td>
                                @item.AssignmentDate.ToString("dd/MM/yyyy")
                            </td>
                            <td>
                                <p style="color:red;">Not Payed</p>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Amount)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PaymentPlan.Name)
                            </td>
                            <td>
                                @foreach (var pItem in item.PaymentPlan.PaymentItem)
                                {
                                    <span>@Html.DisplayFor(model => pItem.Description) |</span>
                                }
                            </td>

                        </tr>
                    }
                }
            </tbody>

        </table>
    </div>



</div>

@{
    int role = 0;

    //Validar si existe la Session
    if (Session["user"] != null)
    {
        Infrastructure.Models.User oUser = (Infrastructure.Models.User)Session["User"];

        if (oUser != null)
        {
            role = oUser.IDRole;
            if (role == 1)
            {
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            }
            else if (role == 2)
            {
                @Html.ActionLink("Pay Debts",
               "PayDebts", null, new { @class = "btn btn-primary" })
            }
        }
    }
}

Web/Views/StatementAccount/Index.cshtml
@model IEnumerable<Infrastructure.Models.Residence>

@{
    ViewBag.Title = "Account Statements";
}

<h2>Account Statements</h2>

<div class="table-responsive ">
    <table class="table table-striped trCustom shadow-lg" id="myTable">
        <thead>
            <tr class="table-dark">
                <th>
                    @Html.DisplayNameFor(model => model.IDResidence)
                </th>
                <th>
                    Owner Name
                </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IDResidence)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.FirstName) @Html.DisplayFor(modelItem => item.User.LastName)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.IDResidence }, new { @class = "btn btn-primary" })
                    </td>
                </tr>
            }
        </tbody>

</table>

</div>
    

Web/Views/StatementAccount/PayDebts.cshtml
@model Infrastructure.Models.Residence
@{
    ViewBag.Title = "Pay Debts";
}

<h2>Pay Debts</h2>


@using (Html.BeginForm("SetDebtsAsPaid", "StatementAccount", FormMethod.Post, new { enctype = "multipart/form-data", @id = "myForm", onsubmit = "return validateForm()" }))
{
    <hr />
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group my-3">
            <label class="control-label">Pending Debts</label>
            <div class="col-md-12">
                @Html.DropDownList("selectedDebts",
               (MultiSelectList)ViewBag.PendingDebts,
               htmlAttributes: new { @class = "form-control", multiple = "multiple", @id = "listItems", required="required", data_val = "true", data_val_required = "You must select at least one option." })
            </div>
            <label class="control-label mt-1">Total</label>
            <input type="text" class="form-control" id="InputTotal" readonly="readonly" required>
        </div>

        <div class="form-group my-3">
            <label class="control-label col-md-2">Payment Method</label>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked required>
                <label class="form-check-label" for="flexRadioDefault2">
                    <img src="~/images/pngwing.com.png" alt="Credit Card" width="100">
                </label>
            </div>
        </div>

        <div class="form-group my-2">
            <label for="InputName" class="form-label">Cardholder Name</label>
            <input type="text" class="form-control" id="InputName" aria-describedby="InputName" name="CardholderName" required oninvalid="this.setCustomValidity('Please enter your cardholder name')" oninput="setCustomValidity('')">
           
        </div>

        <div class="form-group my-2">
            <label for="InputCardN" class="form-label">Card Number</label>
            <input type="text" class="form-control" id="InputCardN" aria-describedby="InputCardN" name="CardNumber" placeholder="**** **** **** ****" required oninvalid="this.setCustomValidity('Please enter your card number')" oninput="setCustomValidity('')">
        </div>

        <div class="form-group my-2 d-flex gap-3">
            <div class="w-50">
                <label for="InputExpire" class="form-label">Expire</label>
                <input type="text" class="form-control" id="InputExpire" aria-describedby="InputExpire" placeholder="MM/YY" required oninvalid="this.setCustomValidity('Please enter the expiration date in MM/YY format')" oninput="setCustomValidity('')">
            </div>
            <div class="w-50">
                <label for="InputCode" class="form-label">Security Code</label>
               
                <input type="text" class="form-control" id="InputCode" pattern="[0-9]{3}" title="Please enter a valid 3-digit security code" aria-describedby="InputCode" placeholder="CVC" minlength="3" required">
            </div>
        </div>



        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Pay" class="btn btn-primary " />
            </div>
        </div>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
    var card = document.getElementById('InputCardN');
    var cname = document.getElementById('InputName');
    var expire = document.getElementById('InputExpire');
    var code = document.getElementById('InputCode');


    $(document).ready(function () {

        var listItems = $('#listItems');
        var total = $('#InputTotal');


        listItems.change(function () {
            var selectedOptions = listItems.find('option:selected');
            var auxTotal = 0;

            selectedOptions.each(function () {
                var texto = $(this).text();
                var price = parseFloat(texto.split('$')[1]);
                auxTotal += price;
            });


            total.val(auxTotal.toFixed(2));
        });

    });


    

    function validateForm() {
        // Accede a los campos del formulario
        var card = $('#InputCardN');
        var cname = $('#InputName');
        var expire = $('#InputExpire');
        var code = $('#InputCode');

        // Validación de campos
        var selectedOptions = document.getElementById("listItems").selectedOptions;
        if (selectedOptions.length == 0) {
            alert("Please select at least one debt");
            return false;
        }
        

        if (card.val().length !== 16 || !/^[0-9]+$/.test(card.val())) {
            alert('Please enter a valid card number');
            card.addClass('is-invalid');
            return false;
        } else {
            card.removeClass('is-invalid');
        }

        if (cname.val().length < 2 || !(/^[a-zA-Z\s]+$/.test(cname.val()))) {
            alert('Please enter a valid Cardholder name');
            cname.addClass('is-invalid');
            return false;
        } else {
            cname.removeClass('is-invalid');
        }

        if (code.val().length !== 3 || !/^[0-9]+$/.test(code.val())) {
            alert('Please enter a valid security code');
            code.addClass('is-invalid');
            return false;
        } else {
            code.removeClass('is-invalid');
        }

        // Obtener la fecha actual
        var now = new Date();
        var currentMonth = now.getMonth() + 1; // Sumar 1 porque getMonth() devuelve un valor de 0 a 11
        var currentYear = now.getFullYear();

        // Validar el formato de la fecha
        if (!/^\d{2}\/\d{2}$/.test(expire.val())) {
            alert('Please enter a valid expiration date');
            expire.addClass('is-invalid');
            return false;
        }

        // Obtener los valores de mes y año
        var month = parseInt(expire.val().substring(0, 2));
        var year = parseInt(expire.val().substring(3, 5)) + 2000; // Sumar 2000 porque se está usando un formato YY

        // Validar que el mes y año sean válidos
        if (month < 1 || month > 12 || year < currentYear) {
            alert('Please enter a valid expiration date');
            expire.addClass('is-invalid');
            return false;
        } else if (year === currentYear && month < currentMonth) {
            alert('The card has expired');
            expire.addClass('is-invalid');
            return false;
        } else {
            expire.removeClass('is-invalid');
            return true;
        }


        

        // Si todas las validaciones son exitosas, devuelve true
        return true;
    }


</script>
}